version: "3.8"

services:
  node:
    container_name: kanji_node
    volumes:
      - .:/usr/src/backend/app
    build: .
    command: npm run dev
    ports:
      - 80:3000
    links:
      - 'mongo'
    env_file:
      - .env
    environment:
      DATABASE_CONNECTION: ${DATABASE_CONNECTION}
      JWT_SECRET: ${JWT_SECRET}
      NEO_USER: ${NEO_USER}
      NEO_PASSWORD: ${NEO_PASSWORD}

  mongo:
    container_name: kanji_mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  neo4j:
    image: neo4j:4.0.3
    container_name: kanji_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo:/data/neo
  neo4j_test:
    image: neo4j:4.0.3
    container_name: kanji_neo4j_test
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - ./data/neo_test:/data/neo_test
